spring:
  profiles:
    active: dev

  jackson.visibility:
    field: any
    getter: none
    setter: none
    is_getter: none

server.servlet.encoding:
  charset: UTF-8
  enabled: true
  force: true